// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type VisualCategory struct {
	CategoryKey   string `json:"categoryKey"`
	CategoryValue string `json:"categoryValue"`
	IsDeleted     int64  `json:"isDeleted"`
	TenantUuid    string `json:"tenantUuid"`
}

type CategoryPageSetResp struct {
	Rows []VisualCategory `json:"rows"`
	PageResp
}

type IdReq struct {
	Id string `form:"id"` // 主键 ID
}

type JsonResp struct {
	Str string `json:"str"` // JSON 配置内容
}

type PageReq struct {
	PageNo   int64  `form:"pageNo,optional"`
	PageSize int64  `form:"pageSize,optional"`
	Sort     string `form:"sort,optional"`
	Order    string `form:"order,optional"`
}

type PageResp struct {
	PageSize   int64 `json:"pageSize"`
	PageNo     int64 `json:"pageNo"`
	TotalPage  int64 `json:"totalPage"`
	TotalCount int64 `json:"totalCount"`
}

type Visual struct {
	Uuid          string `json:"uuid"`
	Title         string `json:"title"`         // 大屏标题
	BackgroundUrl string `json:"backgroundUrl"` // 大屏背景
	Thumbnail     string `json:"thumbnail"`     // 缩略图
	Category      string `json:"category"`      // 大屏类型
	Password      string `json:"password"`      // 大屏发布密码
	Status        int64  `json:"status"`        // 状态
	IsDeleted     int64  `json:"isDeleted"`     // 是否删除
}

type VisualPageSetResp struct {
	Rows []Visual `json:"rows"`
	PageResp
}

type VisualPageSetReq struct {
	PageReq
	Category string `form:"category,optional"`
}
