http:
  routers:
    # System 子路径
    router-system:
      rule: "Host(`api.go-atlas.cn`) && (PathPrefix(`/system`) || PathPrefix(`/auth`))"
      entryPoints:
        - websecure
      service: service-system
      middlewares:
        - cors-header
      tls: {}

    # Monitor
    router-monitor:
      rule: "Host(`api.go-atlas.cn`) && PathPrefix(`/monitor`)"
      entryPoints:
        - websecure
      service: service-monitor
      middlewares:
        - cors-header
      tls: {}

    # Resource
    router-resource:
      rule: "Host(`api.go-atlas.cn`) && PathPrefix(`/resource`)"
      entryPoints:
        - websecure
      service: service-resource
      middlewares:
        - cors-header
      tls: {}

  services:
    service-system:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:8090"

    service-monitor:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:8091"

    service-resource:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:8092"

  middlewares:
    cors-header:
      headers:
        accessControlAllowOriginList:
          - "*"
        accessControlAllowMethods:
          - "GET"
          - "POST"
          - "PUT"
          - "DELETE"
          - "OPTIONS"
        accessControlAllowHeaders:
          - "*"
        accessControlAllowCredentials: true
        addVaryHeader: true
