entryPoints:
  websecure:
    address: :443
  traefik:
    address: :80

api:
  dashboard: true
  insecure: true

providers:
  file:
    filename: "./bin/traefik/dynamic.yaml"
    watch: true

tls:
  certificates:
    - certFile: /opt/ssl/fullchain.cer
      keyFile: /opt/ssl/go-atlas.cn.key

