// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package handler

import (
	"net/http"

	logininfor "monitor/internal/handler/logininfor"
	monitor "monitor/internal/handler/monitor"
	online "monitor/internal/handler/online"
	operLog "monitor/internal/handler/operLog"
	"monitor/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: online.PageSetHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:id",
					Handler: online.OfflineHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/monitor/online"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodDelete,
					Path:    "/clean",
					Handler: operLog.CleanHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:ids",
					Handler: operLog.DeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: operLog.PageSetHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/monitor/operlog"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodDelete,
					Path:    "/clean",
					Handler: logininfor.CleanHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:ids",
					Handler: logininfor.DeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: logininfor.PageSetHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/monitor/logininfor"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/cache",
					Handler: monitor.RedisMonitorHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/monitor"),
	)
}
