// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: desc/desc.proto

package monitor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ping          string                 `protobuf:"bytes,1,opt,name=ping,proto3" json:"ping,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_desc_desc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_desc_desc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_desc_desc_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetPing() string {
	if x != nil {
		return x.Ping
	}
	return ""
}

type LoginInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InfoId        string                 `protobuf:"bytes,11,opt,name=infoId,proto3" json:"infoId,omitempty"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenantId,proto3" json:"tenantId,omitempty"`
	ClientKey     string                 `protobuf:"bytes,3,opt,name=clientKey,proto3" json:"clientKey,omitempty"`
	DeviceType    string                 `protobuf:"bytes,4,opt,name=deviceType,proto3" json:"deviceType,omitempty"`
	Ipaddr        string                 `protobuf:"bytes,5,opt,name=ipaddr,proto3" json:"ipaddr,omitempty"`
	LoginLocation string                 `protobuf:"bytes,6,opt,name=LoginLocation,proto3" json:"LoginLocation,omitempty"`
	Browser       string                 `protobuf:"bytes,7,opt,name=browser,proto3" json:"browser,omitempty"`
	Os            string                 `protobuf:"bytes,8,opt,name=os,proto3" json:"os,omitempty"`
	Status        string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	Msg           string                 `protobuf:"bytes,10,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginInfoReq) Reset() {
	*x = LoginInfoReq{}
	mi := &file_desc_desc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginInfoReq) ProtoMessage() {}

func (x *LoginInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_desc_desc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginInfoReq.ProtoReflect.Descriptor instead.
func (*LoginInfoReq) Descriptor() ([]byte, []int) {
	return file_desc_desc_proto_rawDescGZIP(), []int{1}
}

func (x *LoginInfoReq) GetInfoId() string {
	if x != nil {
		return x.InfoId
	}
	return ""
}

func (x *LoginInfoReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginInfoReq) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *LoginInfoReq) GetClientKey() string {
	if x != nil {
		return x.ClientKey
	}
	return ""
}

func (x *LoginInfoReq) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *LoginInfoReq) GetIpaddr() string {
	if x != nil {
		return x.Ipaddr
	}
	return ""
}

func (x *LoginInfoReq) GetLoginLocation() string {
	if x != nil {
		return x.LoginLocation
	}
	return ""
}

func (x *LoginInfoReq) GetBrowser() string {
	if x != nil {
		return x.Browser
	}
	return ""
}

func (x *LoginInfoReq) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *LoginInfoReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LoginInfoReq) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type OperLogReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 租户编号
	TenantId string `protobuf:"bytes,2,opt,name=tenantId,proto3" json:"tenantId,omitempty"`
	// 模块标题
	Title string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	// 业务类型（0其它 1新增 2修改 3删除）
	BusinessType int32 `protobuf:"varint,4,opt,name=businessType,proto3" json:"businessType,omitempty"`
	// 方法名称
	Method string `protobuf:"bytes,5,opt,name=method,proto3" json:"method,omitempty"`
	// 请求方式
	RequestMethod string `protobuf:"bytes,6,opt,name=requestMethod,proto3" json:"requestMethod,omitempty"`
	// 操作类别（0其它 1后台用户 2手机端用户）
	OperatorType int32 `protobuf:"varint,7,opt,name=operatorType,proto3" json:"operatorType,omitempty"`
	// 操作人员
	OperName string `protobuf:"bytes,8,opt,name=operName,proto3" json:"operName,omitempty"`
	// 部门名称
	DeptName string `protobuf:"bytes,9,opt,name=deptName,proto3" json:"deptName,omitempty"`
	// 请求URL
	OperUrl string `protobuf:"bytes,10,opt,name=operUrl,proto3" json:"operUrl,omitempty"`
	// 主机地址
	OperIp string `protobuf:"bytes,11,opt,name=operIp,proto3" json:"operIp,omitempty"`
	// 操作地点
	OperLocation string `protobuf:"bytes,12,opt,name=operLocation,proto3" json:"operLocation,omitempty"`
	// 请求参数
	OperParam string `protobuf:"bytes,13,opt,name=operParam,proto3" json:"operParam,omitempty"`
	// 返回参数
	JsonResult string `protobuf:"bytes,14,opt,name=jsonResult,proto3" json:"jsonResult,omitempty"`
	// 操作状态（0正常 1异常）
	Status int32 `protobuf:"varint,15,opt,name=status,proto3" json:"status,omitempty"`
	// 错误消息
	ErrorMsg string `protobuf:"bytes,16,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
	// 消耗时间
	CostTime      int64 `protobuf:"varint,18,opt,name=costTime,proto3" json:"costTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperLogReq) Reset() {
	*x = OperLogReq{}
	mi := &file_desc_desc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperLogReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperLogReq) ProtoMessage() {}

func (x *OperLogReq) ProtoReflect() protoreflect.Message {
	mi := &file_desc_desc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperLogReq.ProtoReflect.Descriptor instead.
func (*OperLogReq) Descriptor() ([]byte, []int) {
	return file_desc_desc_proto_rawDescGZIP(), []int{2}
}

func (x *OperLogReq) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *OperLogReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *OperLogReq) GetBusinessType() int32 {
	if x != nil {
		return x.BusinessType
	}
	return 0
}

func (x *OperLogReq) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *OperLogReq) GetRequestMethod() string {
	if x != nil {
		return x.RequestMethod
	}
	return ""
}

func (x *OperLogReq) GetOperatorType() int32 {
	if x != nil {
		return x.OperatorType
	}
	return 0
}

func (x *OperLogReq) GetOperName() string {
	if x != nil {
		return x.OperName
	}
	return ""
}

func (x *OperLogReq) GetDeptName() string {
	if x != nil {
		return x.DeptName
	}
	return ""
}

func (x *OperLogReq) GetOperUrl() string {
	if x != nil {
		return x.OperUrl
	}
	return ""
}

func (x *OperLogReq) GetOperIp() string {
	if x != nil {
		return x.OperIp
	}
	return ""
}

func (x *OperLogReq) GetOperLocation() string {
	if x != nil {
		return x.OperLocation
	}
	return ""
}

func (x *OperLogReq) GetOperParam() string {
	if x != nil {
		return x.OperParam
	}
	return ""
}

func (x *OperLogReq) GetJsonResult() string {
	if x != nil {
		return x.JsonResult
	}
	return ""
}

func (x *OperLogReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *OperLogReq) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *OperLogReq) GetCostTime() int64 {
	if x != nil {
		return x.CostTime
	}
	return 0
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pong          string                 `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_desc_desc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_desc_desc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_desc_desc_proto_rawDescGZIP(), []int{3}
}

func (x *Response) GetPong() string {
	if x != nil {
		return x.Pong
	}
	return ""
}

type EmptyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyResp) Reset() {
	*x = EmptyResp{}
	mi := &file_desc_desc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyResp) ProtoMessage() {}

func (x *EmptyResp) ProtoReflect() protoreflect.Message {
	mi := &file_desc_desc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyResp.ProtoReflect.Descriptor instead.
func (*EmptyResp) Descriptor() ([]byte, []int) {
	return file_desc_desc_proto_rawDescGZIP(), []int{4}
}

var File_desc_desc_proto protoreflect.FileDescriptor

const file_desc_desc_proto_rawDesc = "" +
	"\n" +
	"\x0fdesc/desc.proto\x12\amonitor\"\x1d\n" +
	"\aRequest\x12\x12\n" +
	"\x04ping\x18\x01 \x01(\tR\x04ping\"\xae\x02\n" +
	"\fLoginInfoReq\x12\x16\n" +
	"\x06infoId\x18\v \x01(\tR\x06infoId\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\btenantId\x18\x02 \x01(\tR\btenantId\x12\x1c\n" +
	"\tclientKey\x18\x03 \x01(\tR\tclientKey\x12\x1e\n" +
	"\n" +
	"deviceType\x18\x04 \x01(\tR\n" +
	"deviceType\x12\x16\n" +
	"\x06ipaddr\x18\x05 \x01(\tR\x06ipaddr\x12$\n" +
	"\rLoginLocation\x18\x06 \x01(\tR\rLoginLocation\x12\x18\n" +
	"\abrowser\x18\a \x01(\tR\abrowser\x12\x0e\n" +
	"\x02os\x18\b \x01(\tR\x02os\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12\x10\n" +
	"\x03msg\x18\n" +
	" \x01(\tR\x03msg\"\xe0\x03\n" +
	"\n" +
	"OperLogReq\x12\x1a\n" +
	"\btenantId\x18\x02 \x01(\tR\btenantId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\"\n" +
	"\fbusinessType\x18\x04 \x01(\x05R\fbusinessType\x12\x16\n" +
	"\x06method\x18\x05 \x01(\tR\x06method\x12$\n" +
	"\rrequestMethod\x18\x06 \x01(\tR\rrequestMethod\x12\"\n" +
	"\foperatorType\x18\a \x01(\x05R\foperatorType\x12\x1a\n" +
	"\boperName\x18\b \x01(\tR\boperName\x12\x1a\n" +
	"\bdeptName\x18\t \x01(\tR\bdeptName\x12\x18\n" +
	"\aoperUrl\x18\n" +
	" \x01(\tR\aoperUrl\x12\x16\n" +
	"\x06operIp\x18\v \x01(\tR\x06operIp\x12\"\n" +
	"\foperLocation\x18\f \x01(\tR\foperLocation\x12\x1c\n" +
	"\toperParam\x18\r \x01(\tR\toperParam\x12\x1e\n" +
	"\n" +
	"jsonResult\x18\x0e \x01(\tR\n" +
	"jsonResult\x12\x16\n" +
	"\x06status\x18\x0f \x01(\x05R\x06status\x12\x1a\n" +
	"\berrorMsg\x18\x10 \x01(\tR\berrorMsg\x12\x1a\n" +
	"\bcostTime\x18\x12 \x01(\x03R\bcostTime\"\x1e\n" +
	"\bResponse\x12\x12\n" +
	"\x04pong\x18\x01 \x01(\tR\x04pong\"\v\n" +
	"\tEmptyResp2A\n" +
	"\fLoginInfoRpc\x121\n" +
	"\x04Save\x12\x15.monitor.LoginInfoReq\x1a\x12.monitor.EmptyResp2=\n" +
	"\n" +
	"OperLogRpc\x12/\n" +
	"\x04Save\x12\x13.monitor.OperLogReq\x1a\x12.monitor.EmptyRespB\vZ\t./monitorb\x06proto3"

var (
	file_desc_desc_proto_rawDescOnce sync.Once
	file_desc_desc_proto_rawDescData []byte
)

func file_desc_desc_proto_rawDescGZIP() []byte {
	file_desc_desc_proto_rawDescOnce.Do(func() {
		file_desc_desc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_desc_desc_proto_rawDesc), len(file_desc_desc_proto_rawDesc)))
	})
	return file_desc_desc_proto_rawDescData
}

var file_desc_desc_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_desc_desc_proto_goTypes = []any{
	(*Request)(nil),      // 0: monitor.Request
	(*LoginInfoReq)(nil), // 1: monitor.LoginInfoReq
	(*OperLogReq)(nil),   // 2: monitor.OperLogReq
	(*Response)(nil),     // 3: monitor.Response
	(*EmptyResp)(nil),    // 4: monitor.EmptyResp
}
var file_desc_desc_proto_depIdxs = []int32{
	1, // 0: monitor.LoginInfoRpc.Save:input_type -> monitor.LoginInfoReq
	2, // 1: monitor.OperLogRpc.Save:input_type -> monitor.OperLogReq
	4, // 2: monitor.LoginInfoRpc.Save:output_type -> monitor.EmptyResp
	4, // 3: monitor.OperLogRpc.Save:output_type -> monitor.EmptyResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_desc_desc_proto_init() }
func file_desc_desc_proto_init() {
	if File_desc_desc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_desc_desc_proto_rawDesc), len(file_desc_desc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_desc_desc_proto_goTypes,
		DependencyIndexes: file_desc_desc_proto_depIdxs,
		MessageInfos:      file_desc_desc_proto_msgTypes,
	}.Build()
	File_desc_desc_proto = out.File
	file_desc_desc_proto_goTypes = nil
	file_desc_desc_proto_depIdxs = nil
}
