// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package handler

import (
	"net/http"

	category "report/internal/handler/category"
	visual "report/internal/handler/visual"
	"report/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/getPageSet",
				Handler: category.GetPageSetHandler(serverCtx),
			},
		},
		rest.WithPrefix("/report/reportVisualCategory"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/detail",
				Handler: visual.DetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/getPageSet",
				Handler: visual.GetPageSetHandler(serverCtx),
			},
		},
		rest.WithPrefix("/report/reportVisual"),
	)
}
