// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package handler

import (
	"net/http"

	oss "resource/internal/handler/oss"
	ossconfig "resource/internal/handler/oss/config"
	"resource/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/upload",
					Handler: oss.UploadHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:ids",
					Handler: oss.DeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: oss.PageSetHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/resource/oss"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: ossconfig.InfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: ossconfig.AddHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:ids",
					Handler: ossconfig.DeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/changeStatus",
					Handler: ossconfig.ChangeStatusHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/",
					Handler: ossconfig.UpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: ossconfig.PageSetHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/resource/oss/config"),
	)
}
